### ISSUE TITLE
'metamod_oslink.h' file not found [BUILD ERROR]

### ISSUE THREAD

**Issue by alerad** [Source2ZE/CS2Fixes#110]
I see that plat.h has 

```#include "metamod_oslink.h"```

Yet I can't see the file anywhere, is this issue related to a wrong env var for the metamod path or something else?

I'm importing metamod like this:

```export MMSOURCE112=/home/myuser/workspace/CS2Fixes/build/metamod```

Where metamod contains /addons/etc

Thanks!

Full error:

```
In file included from /home/myuser/workspace/CS2Fixes/src/utils/plat_unix.cpp:21:
/home/myuser/workspace/CS2Fixes/src/utils/plat.h:22:10: fatal error: 'metamod_oslink.h' file not found
#include "metamod_oslink.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
Build failed: cs2fixes/linux-x86_64/src_utils_plat_unix.o

```

**Comment by Vauff** [comment]
For general assistance with build environment problems, you can [join our Discord](https://discord.gg/QsSGf9ZEVs). Since both our Linux and Windows actions builds are passing, this is not an issue with the plugin.

**Comment by kelvinthh** [comment]
> I see that plat.h has
> 
> `#include "metamod_oslink.h"`
> 
> Yet I can't see the file anywhere, is this issue related to a wrong env var for the metamod path or something else?
> 
> I'm importing metamod like this:
> 
> `export MMSOURCE112=/home/myuser/workspace/CS2Fixes/build/metamod`
> 
> Where metamod contains /addons/etc
> 
> Thanks!
> 
> Full error:
> 
> ```
> In file included from /home/myuser/workspace/CS2Fixes/src/utils/plat_unix.cpp:21:
> /home/myuser/workspace/CS2Fixes/src/utils/plat.h:22:10: fatal error: 'metamod_oslink.h' file not found
> #include "metamod_oslink.h"
>          ^~~~~~~~~~~~~~~~~~
> 1 error generated.
> Build failed: cs2fixes/linux-x86_64/src_utils_plat_unix.o
> ```

For those who're wondering, it is not Metamod: Source build you download from their website, it's asking for the source code, so go git clone the mmsource project and point to that directory instead. The readme is so confusing.
