### ISSUE TITLE
[REQ] Surf ramps fix

### ISSUE THREAD

**Issue by DaLLuZZ** [Source2ZE/CS2Fixes#115]
Hi, it would be nice to implement this fix
https://github.com/GAMMACASE/MomSurfFix

the purpose of it is to fix this kind of bug, which occurred very often in vanilla csgo, and which also occurs in vanilla cs2
https://www.youtube.com/watch?v=LhA7RZ1Sv7Y

**Comment by xen-000** [comment]
The nature of ramp bugs in source2 is not the same as with source1, simply implementing that plugin will not do. Also, I'd much rather see valve fix the issue instead of having to rely on yet another server-side fix.
