### ISSUE TITLE
Admin commands not working

### ISSUE THREAD

**Issue by Draakoor** [Source2ZE/CS2Fixes#116]
Hi there I setup my admin permissions but I cant use any commands.
my admin cfg:
<img width="555" alt="image" src="https://github.com/Source2ZE/CS2Fixes/assets/11836348/7db52f68-8a29-479a-af93-c6f69d9a6420">

**Comment by xLeviNx** [comment]
Was that file saved into the correct directory and loaded?
Do you see any comments regarding admin output in console?

**Comment by xen-000** [comment]
It's also possible that you're not getting steam authenticated in the first place.

**Comment by Vauff** [comment]
Your file is named `admin.cfg`. This is incorrect, and it should be named `admins.cfg`.
