### ISSUE TITLE
PlayerPawns still present in the game after disconnect and max team size locked to 5

### ISSUE THREAD

**Issue by NervzZ** [Source2ZE/CS2Fixes#118]
Hello

I'm using this plugin primarily for the trigger push fix for my surf server and I noticed that playerpawns are still left in the game when they disconnect which is a bit weird. I didn't find any variable from the cfg to edit that.

Also I noticed that using your plugin I'm having a weird issue with team size being maximum 5. I used mp_teamautobalance 0 and mp_limitteams 0 yet it still doesn't let me have more than 5 players per team. I don't know if other commands of my configs could have any conflicts with the mod.

**Comment by Poggicek** [comment]
What exactly makes you think all of this is being caused by cs2fixes

**Comment by NervzZ** [comment]
Without using it I don't have these issues pretty much so I do suspect there's something going on there perhaps? The only other plugins I have installed is counterstrikesharp with my own fairly light plugin that isn't doing much. Through every evolution of my own script these things have been an issue as long as CS2Fixes was loaded.

I would be happy to try something else if I had better knowledge to compiler a lighter plugin that only does the trigger push fix though and maybe see if my issues indeed disappear.

**Comment by NervzZ** [comment]
By Pawns I mean the physical player in the game (not the controller) basically after player disconnect the pawn is still just respawning and you can kill it even. You do not see anyone in the scoreboard corresponding to that entity.

So that's how I noticed the pawns are still there.
I've had this issue on surf maps (any) and did not try on official maps to see if that is still an issue. It only occurred since using CS2Fixes.

Anyhow I guess I could go on with more random testing to see if this specific issue is not happening in different context. 

If I don't find anything relevant I'll probably just compile a version that only does the trigger push fix since I only use the plugin for this feature.

**Comment by audiomaster99** [comment]
> By Pawns I mean the physical player in the game (not the controller) basically after player disconnect the pawn is still just respawning and you can kill it even. You do not see anyone in the scoreboard corresponding to that entity.
> 
> So that's how I noticed the pawns are still there. I've had this issue on surf maps (any) and did not try on official maps to see if that is still an issue. It only occurred since using CS2Fixes.
> 
> Anyhow I guess I could go on with more random testing to see if this specific issue is not happening in different context.
> 
> If I don't find anything relevant I'll probably just compile a version that only does the trigger push fix since I only use the plugin for this feature.

mp_disconnect_kills_players 1

**Comment by NervzZ** [comment]
I'll try this and see if that helps but I suspect the pawn will still respawn as it shouldn't be any different than killing them manually.

**Comment by NervzZ** [comment]
Yeah it didn't help as I expected, pawn still present in the map without the actual player being connected.
