### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by es3n1n** [Source2ZE/CS2Fixes#126]
Hey guys! Since you are using some of our [reversals](https://github.com/Source2ZE/CS2Fixes/blob/main/src/cs2_sdk/interfaces/cschemasystem.h
), maybe it would be also nice to 
* update the structs
* follow the license and leave the credits

**Comment by xen-000** [comment]
The code was taken from elsewhere so I never realized it came from source2gen, thanks for bringing attention to it.

**Comment by Vauff** [comment]
https://github.com/Source2ZE/CS2Fixes/commit/e331101e8462708980d7de35343c255f4939a3ec
