### ISSUE TITLE
Is there plans to make a slim version of CS2Fixes?

### ISSUE THREAD

**Issue by justinnobledev** [Source2ZE/CS2Fixes#130]
With things like CounterStrikeSharp starting to take off and people making basic admin commands for it is there plans to release either a slim version of CS2Fixes that doesn't have commands and is purely fixes or have cvars for turning on and off the various commands?

**Comment by justinnobledev** [comment]
> You should take a look at the commits and see what is being done in the other branches.

I just double checked all the other branches and the current commits to main and saw nothing about this. There is a slight mention in the readme but no where mentions if this is going to happen soonish or 6 months from now. Currently CS2Fixes is the only way to have trigger_push fix and a few other things so its necessary on almost any movement server, but it then adds a lot of stuff that might not be wanted like rtv for example.

**Comment by xen-000** [comment]
There's a toggle for the whole vote manager system (including RTV), `cs2f_votemanager_enable`, which will be in the next release.

**Comment by justinnobledev** [comment]
> There's a toggle for the whole vote manager system (including RTV), `cs2f_votemanager_enable`, which will be in the next release.

Thanks for that! But is there plans to make it so we can disable commands and stuff to?

**Comment by Vauff** [comment]
> > There's a toggle for the whole vote manager system (including RTV), `cs2f_votemanager_enable`, which will be in the next release.
> 
> Thanks for that! But is there plans to make it so we can disable commands and stuff to?

`cs2f_commands_enable` and `cs2f_admin_commands_enable` are now available.
