### ISSUE TITLE
Admin stop getting authenticated after a while

### ISSUE THREAD

**Issue by audiomaster99** [Source2ZE/CS2Fixes#142]
hey, i just compiled latest commit, and for some reason after some time if i enter the server i dont get authenticated as admin(and i have to restart the server, reloading admins dosen't help), can someone tell me if i can fix this somehow?

**Comment by audiomaster99** [comment]
It seems the problem does not happen anymore....
I think issue was compatibility with counter strike sharp (after updateing css, problem seems to be resolved)

**Comment by Vauff** [comment]
This was found to be an issue that occurs after 73 hours of server uptime, https://github.com/Source2ZE/CS2Fixes/commit/280e1db70b35026a4f55a36eb61d8b4298515ec8 fixes it and will be merged into main in the future.
