### ISSUE TITLE
[Bug] Server crash from SwitchTeam (cs2f_force_ct)

### ISSUE THREAD

**Issue by axl303** [Source2ZE/CS2Fixes#155]
Hello, when cvar is set to 1 - to force everyone to CTs on every new round (SwitchTeam function), the server crash.
`cs2f_force_ct  0 // Whether to force everyone to CTs on every new round`
Tested on OS: Linux Debian 12 with newest metamod (1278 build), the plugin is compiled on my PC (linux debian 12 also).
Should I provide more information and if needed what should I provide?

**Comment by Vauff** [comment]
If you can recreate this with an official release, download [Accelerator](https://github.com/komashchenko/AcceleratorLocal) and share the crash stack trace & CS2Fixes version here, so we can debug. Note we cannot debug third-party builds for technical reasons.

As for fixing your own build, have you tried compiling in SteamRT3 (or Debian 11)? Newer toolchains are not well tested.

**Comment by axl303** [comment]
Sorry for the delay!

> If you can recreate this with an [official release](https://github.com/Source2ZE/CS2Fixes/releases), install [Accelerator](https://github.com/komashchenko/AcceleratorLocal/releases) and share the crash stack trace & CS2Fixes version here, so we can debug. Note we cannot debug third-party builds for technical reasons.

I downloaded the latest version (v1.2 from Releases) and everything works fine (No crashes). Tested it multiple times to be sure.

> As for fixing your own build, have you tried compiling in SteamRT3 (or Debian 11)? Newer toolchains are not well tested.

My build is not much different from this one in the repository, just compiled locally on my pc. I will be testing it on Debian 11 as you said when I have some free time.

Thank you for the detailed information you gave. :)
