### ISSUE TITLE
Cancel respawning zombies from after death

### ISSUE THREAD

**Issue by t4r1k58** [Source2ZE/CS2Fixes#161]
Is this possible? Can respawning after killing zombies be turned off? zr_respawn_delay 0 attempted.

**Comment by Vauff** [comment]
Implemented in https://github.com/Source2ZE/CS2Fixes/commit/4e8fa7648619094850bcce25195852bab4973047, negative values (e.g. `zr_respawn_delay -1`) will now immediately disable respawn after first infection. This will be merged to main and make its way to a new release in the future.
