### ISSUE TITLE
Glitch where bots that respawn after placing bombs stop moving.

### ISSUE THREAD

**Issue by Nononshidanku** [Source2ZE/CS2Fixes#162]
Actually, this glitch has been around since the CS:S,
Valve doesn't seem to want to fix it.

**Comment by Vauff** [comment]
If I understand correctly this is a game issue, then this is probably fairly out of scope for us. Our recent bot work has only been for the purpose of having "dummy" bots we can use for testing things with multiple players.

**Comment by Vauff** [comment]
Going to close this, as I don't ever see us fixing it. We have no plans of modifying bot behaviour, and bomb behaviour is even further out of scope for our zombie escape focus.
