### ISSUE TITLE
Incorrect pszNetworkID in Hook_ClientDisconnect

### ISSUE THREAD

**Issue by mixern6** [Source2ZE/CS2Fixes#164]
In the server logs I have messages like:

> [CS2Fixes] Hook_ClientDisconnect(1, 2, "WhiteBird", 76561799548469999, "䴙Z")
> [CS2Fixes] Hook_ClientDisconnect(4, 2, "stolone888", 76561199576879999, "ோ")
> [CS2Fixes] Hook_ClientDisconnect(1, 54, "AVGNEL", 76561198918919999, "[U:1:258647999]")
> [CS2Fixes] Hook_ClientDisconnect(2, 1, "Appu69", 76561119033259999, "weapon_fauxitemid")
> [CS2Fixes] Hook_ClientDisconnect(1, 2, "Mr.Hat", 76562199593249999, "`홻�")

> [CS2Fixes] Hook_ClientDisconnect(1, 2, "enot9ui", 76561199348469999, "F2Z")
> [CS2Fixes] Hook_ClientDisconnect(0, 59, "stul9l6", 76561199043259999, "`*G2Z")

The last argument of the function is incorrect.  There is a potential access violation here.

**Comment by Vauff** [comment]
We're using the definition from [hl2sdk](https://github.com/alliedmodders/hl2sdk/blob/e8226b297c84ecee739818f4a97c1d545412fdcd/public/eiface.h#L565-L566) here. Maybe needs to be reported that the `pszNetworkID` param is wrong.

**Comment by Vauff** [comment]
Can be considered fixed on our end by https://github.com/Source2ZE/CS2Fixes/commit/d7808f5ce224a2eb4e74cbe07dd344a5be7a1f3e.
