### ISSUE TITLE
ammo_grenade_limit_default & zr_infinite_ammo incompatibility

### ISSUE THREAD

**Issue by mepoo-github** [Source2ZE/CS2Fixes#167]
`ammo_grenade_limit_default 2` and `zr_infinite_ammo 1` in conjunction causes infinite grenade respawning.

**Comment by xLeviNx** [comment]
Is this an actual bug or user error? I haven't noticed this issue on zr since lua or latest branch

**Comment by Vauff** [comment]
> Is this an actual bug or user error? I haven't noticed this issue on zr since lua or latest branch

I already reproduced this bug.

**Comment by Vauff** [comment]
Fixed in https://github.com/Source2ZE/CS2Fixes/commit/60709674bae73ed85e65ad7ed4a6ee531349da95. This will be merged to main and make its way to a new release in the future.
