### ISSUE TITLE
Unlocked to use grenade smoke decoys...

### ISSUE THREAD

**Issue by mepoo-github** [Source2ZE/CS2Fixes#168]
Unlocked to use grenade smoke decoys...

**Comment by Vauff** [comment]
Assuming this is ZR related, you can "unlock" other grenades in `addons/cs2fixes/configs/zr/weapons.cfg` by setting `"enabled" "1"`, however they do not have any special functionality.

If you are requesting new custom grenade implementations, please be a **lot** more specific.

**Comment by mepoo-github** [comment]
thank you
