### ISSUE TITLE
Unlock console server spam kick bot with bot_quota.

### ISSUE THREAD

**Issue by mepoo-github** [Source2ZE/CS2Fixes#169]
Unlock console server spam kick bot with bot_quota.

**Comment by Vauff** [comment]
Please provide more information.

**Comment by mepoo-github** [comment]
Can't use add bots

**Comment by Vauff** [comment]
You need to do some basic debug on your own to provide better reproduction steps in the future, this gives us almost nothing to work with.

Regardless, this has nothing to do with CS2Fixes and is base game behaviour. Changing `bot_quota` once a round is further underway (after ~30 seconds) does not appear to take effect immediately. You can restart the round or set `bot_quota` sooner to work around this.
