### ISSUE TITLE
Make reload_map_list runnable by server

### ISSUE THREAD

**Issue by ws-cs2** [Source2ZE/CS2Fixes#170]
https://github.com/Source2ZE/CS2Fixes/blob/2d44f44ac1961ba8a80dcb5098806f3bea1ef463/src/map_votes.cpp#L40

My use case is on boot my server makes the maplist.cfg from the workshop collection its started with, but then it can't run this command

**Comment by Vauff** [comment]
The server [bypasses admin flags](https://github.com/Source2ZE/CS2Fixes/blob/2d44f44ac1961ba8a80dcb5098806f3bea1ef463/src/commands.h#L57-L59), and I personally have no issues running `c_reload_map_list` from server console. Are you sure this issue is on our end?

**Comment by ws-cs2** [comment]
> The server [bypasses admin flags](https://github.com/Source2ZE/CS2Fixes/blob/2d44f44ac1961ba8a80dcb5098806f3bea1ef463/src/commands.h#L57-L59), and I personally have no issues running `c_reload_map_list` from server console. Are you sure this issue is on our end?

Sorry, you are correct. I didn't realize that executing these commands from console required the `c_` prefix
