### ISSUE TITLE
feat: Infinity Ammo

### ISSUE THREAD

**Issue by xLeviNx** [Source2ZE/CS2Fixes#171]
Move Infinity ammo outside of Zombie Reborn (make it not depend on Zombie Reborn). At the moment, cs2fixes has the best implementation of infinite ammo without it effecting nades.

**Comment by Vauff** [comment]
Implemented in https://github.com/Source2ZE/CS2Fixes/commit/60709674bae73ed85e65ad7ed4a6ee531349da95. This will be merged to main and make its way to a new release in the future.
