### ISSUE TITLE
Adding bots makes them disconnect and connect nonstop.

### ISSUE THREAD

**Issue by JayCroghan** [Source2ZE/CS2Fixes#185]
bot_quota in cs2fixes.cfg 0 or 10 or 1, zr_enable 1 in cs2fixes.cfg, that's the only changes to the repo, bot_add and they just start disconnecting and reconnecting like crazy.

**Comment by Vauff** [comment]
I know @Hichatu can reproduce this but I still can't, going to need more information to identify it.

**Comment by JayCroghan** [comment]
Clean CS2 install. Installed MetaMod with GameInfo. Clean clone of CS2Fixes fix-cs2-update branch, configure (as per readme) and ambuild using metamod source from February 6. Only thing they have done since then is add something to shut up some warning in msvc. SDK is the one included in the clone.

Switch zr_enable 1 in cs2fixes.cfg and bot_quota 0, or 1 or 10, anything, in cs2fixes.cfg. No other changes.

Once the map loads, type bot_add a couple of times. To start the mayhem I need to join with my client. I just noticed today I didn't mention that step. Having bot_quota 10 in the config before I join the server is quiet. When I leave the game the mayhem of bots reconnecting constantly stops again. Sorry for not adding this earlier.

What other information can I supply?

**Comment by lucasgf00** [comment]
in the server start.bat do game_mode 0 instead of 1. That will fix the bot issue

**Comment by Vauff** [comment]
Can you confirm this still happens with v1.8? https://github.com/Source2ZE/CS2Fixes/commit/b90c072b8f852c6b9e7114a00a385da1fc9aaeff may have fixed the issue.

**Comment by xLeviNx** [comment]
This is fixed and works fine

**Comment by Vauff** [comment]
Also just found https://github.com/Source2ZE/CS2Fixes/commit/7d213cba2c9efbf34a718722c7aac897c8789023, *surely* all causes of this are fixed now, so I'm just going to close this.
