### ISSUE TITLE
Binds Issues

### ISSUE THREAD

**Issue by giurlaninick** [Source2ZE/CS2Fixes#204]
**Crosspost from https://gflclan.com/topic/86469-add-support-for-and-console-commands-in-addition-to-c_-console-commands/ on behalf of OP**

There are a number of server commands that are listed in this topic: https://gflclan.com/topic/86115-cs2-ze-server-information/.

In CS:GO I had all my keybindings for server commands configured in my autoexec.cfg in the following "say-format":           bind "key" "say /command".
It was also possible to use ! instead of / in say-format server commands. Say-format server commands also worked in console.

This is still true on Net4all CS2 server, i.e. say-format server commands work there in console and with keybindings.

On GFL and Mapeadores servers say-format server commands don't work as expected, and it is proposed to use server commands in console in the following "c-format": c_command. Keybindings in c-format look like this: bind "key" "c_command".

Net4all server doesn't have support for c-format console commands, though.

Could you, please, add support for the old-style say-format console commands in addition to the new-style c-format console commands? This would enable to use the same keybindings on different CS2 ZE servers.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
On GFL and Mapeadores currently odd things happen when trying to use say-format commands in console and with keybindings. In console:

– say !command (for example say !nomlist) - prints !command in chat but has no effect;
– say "!command" - prints !command in chat and has the desired effect;
– bind "key" "say !command" gets interpreted as bind scancodeXX "say !command". Using this keybinding prints !command in chat but has no effect;
– bind "key" "say "!command"" gets interpreted as bind scancodeXX "say  !command " (the extra quotes are interpreted as spaces). Using this keybinding prints !command in chat but has no effect.

If you replace ! with / in the above commands the effect is the same, except nothing is printed in chat.
I've discovered that if you type ! command or ! command  (same for / command or / command ) in chat, i.e. add a space or a couple of spaces, it has the desired effect.

This console command: bind "key" "say ! command" gets interpreted as bind scancodeXX "say ! command". Using this keybinding prints ! command in chat and it has the desired effect.

The same console command with / instead of !, i.e. bind "key" "say / command" gets interpreted as
bind scancodeXX "say / command", but it has no effect.

Add a space at the end of the above console command, and the keybinding stars working: bind "key" "say / command " gets interpreted as bind scancodeXX "say / command ". It prints nothing in chat (of course), but has the desired effect.

If you replace the extra spaces with extra quotes in the previously mentioned command, the quotes get interpreted as spaces, so the result is the same: bind "key" "say /"command"" gets interpreted as bind scancodeXX "say / command ". It prints nothing in chat, but has the desired effect.

So the following keybindings are possible in my autoexec.cfg on GFL and Mapeadores (as an example):

– bind "q" "say / p90 "   (with extra spaces):
– bind "e" "say /"bizon"" (with extra quotes, interpreted as spaces);
– bind "kp_4" "say / maplist " (with extra spaces);
– bind "kp_5" "say /"nomlist"" (with extra quotes, interpreted as spaces).

Using them prints nothing in chat and they have the desired effect. However, the problem still remains: you have to use different keybindings (old-style vs. new-style) on different CS2 ZE servers.

**Comment by Vauff** [comment]
I believe this is a CS2 command processing quirk, not necessarily anything we're doing wrong. The other server likely has added some sort of workaround for this, which we could possibly do as well.

**Comment by JacobLikesBagels** [comment]
Thanks @giurlaninick, you're a lifesaver!

**Comment by Vauff** [comment]
Fixed in https://github.com/Source2ZE/CS2Fixes/commit/4563f04efec68980240b86d3b9faad61295f1a7f
