### ISSUE TITLE
[Question] HTTP and Gamerules

### ISSUE THREAD

**Issue by Gawnz1** [Source2ZE/CS2Fixes#205]
Hello,

I have two simple questions:

How to use/how to make a HTTP request
When I try to make a request using command: `!http get domain.com` 
it always prints a message:
 `HTTP request to domain.com failed with status code 0`

Is is something from my side or not using something correctly? OS is linux debian 12

The second question is how can I detect the TerminateRound from Gamerules and block a specific event like game commencing (Gamestart)?
https://github.com/Source2ZE/CS2Fixes/blob/main/src/cs2_sdk/entity/cgamerules.h

I know Issues are not a help forum and something, but I am bugging my head 3 days to learn how to do it...

A little help for the both questions would be much appreciated! ❤️

**Comment by axl303** [comment]
> The second question is how can I detect the TerminateRound from Gamerules and block a specific event like game commencing (Gamestart)? https://github.com/Source2ZE/CS2Fixes/blob/main/src/cs2_sdk/entity/cgamerules.h
> 

You need to hook or detect the TerminateRound event for this.
In sourcemod was OnTerminateRound, then you need to check the reason of termination e.g GameStart, but here I am not sure how things work.


Maybe in this detour (I am just guessing): https://github.com/Source2ZE/CS2Fixes/blob/40a7f3d9f479aeb8f1d0a5acb61d615c07176e43/src/detours.cpp#L68
Or you need to hook the event somewhere else, not fully sure and don't know how to do it.
Just trying to help and gave you some information that I think it can help you a bit.

**Comment by Vauff** [comment]
Future questions can go to our [Discord](https://discord.gg/QsSGf9ZEVs), for faster response.

> How to use/how to make a HTTP request When I try to make a request using command: `!http get domain.com` it always prints a message: `HTTP request to domain.com failed with status code 0`
> 
> Is is something from my side or not using something correctly? OS is linux debian 12

Our HTTP API is only built for interacting with REST API's, `domain.com` is simply a normal website not implementing REST standards, thus it won't work.

> The second question is how can I detect the TerminateRound from Gamerules and block a specific event like game commencing (Gamestart)? https://github.com/Source2ZE/CS2Fixes/blob/main/src/cs2_sdk/entity/cgamerules.h

[Declare a detour](https://github.com/Source2ZE/CS2Fixes/blob/d1c44ec491b464ebe05cfa2aefec2fba4034e054/src/detours.cpp#L61) and define it like the other detours are below. The sig is already available in gamedata as `CGameRules_TerminateRound`, and you can use the function definition from [here](https://github.com/Source2ZE/CS2Fixes/blob/d1c44ec491b464ebe05cfa2aefec2fba4034e054/src/addresses.h#L84).
