### ISSUE TITLE
Commands Caps

### ISSUE THREAD

**Issue by axl303** [Source2ZE/CS2Fixes#209]
Hello,

Is it possible to make the commands working even when typed with CAPS ON.

Example:
If I write !command - it works, and if with caps on !COMMAND - it doesn't work.

This might be in favor of users accidently typing with caps enabled/ease of use commands with forgotten caps enabled and so on...

**Comment by Vauff** [comment]
Implemented in https://github.com/Source2ZE/CS2Fixes/commit/443fa88592aa04189ba87059b519e213e0a3b80a
