### ISSUE TITLE
Keep team score same/Don't reset team score

### ISSUE THREAD

**Issue by Gck111** [Source2ZE/CS2Fixes#213]
Hi people. How can I keep the team scores the same (to not reset them) 

I will explain: If team scores are 2:0 for example and if I join empty server, the score resets to 0:0. Same thing is happening when I have joined a team and another player join the opposite team.

**Comment by Vauff** [comment]
Doesn't seem to be an issue on our end, I can recreate this without CS2Fixes installed.
