### ISSUE TITLE
CounterStrikeSharp silent trigger

### ISSUE THREAD

**Issue by daffyyyy** [Source2ZE/CS2Fixes#217]
CS2Fixes blocks the ability to use `/` in chat, it is a silent trigger in css. Is it possible to use this together with cs2fixes?

**Comment by Vauff** [comment]
We have silent `/` triggers on our own commands, making them silent involves blocking the chat message, which also blocks other plugins like CS# ability to receive. Realistically this does not have an easy solution.

However, ideally we should still be able to support this with `cs2f_commands_enable 0`, currently we don't, but it's a small fix I can do later.

**Comment by Vauff** [comment]
https://github.com/Source2ZE/CS2Fixes/commit/50ac172c84a79feee7881126955b39bc90aa8f39
