### ISSUE TITLE
 Configure failed: No suitable C/C++compiler was found

### ISSUE THREAD

**Issue by KefengYimeng** [Source2ZE/CS2Fixes#238]
I followed the operating steps and achieved py/ Configure.py -- enable optimize -- symbol files -- sdks cs2, but at this step, it prompted me that I couldn't find the C \ C++compilation tool. I downloaded minGW and w64devkit, but they didn't work. I don't know which step the problem was. My operating system is win10-64bit

**Comment by Vauff** [comment]
Already assisting on Discord, this is not a bug as our CI builds fine.

For future reference, MinGW should not be used (build with VS on Windows, or build in Linux).
