### ISSUE TITLE
New Server + maplist enabled.

### ISSUE THREAD

**Issue by xLeviNx** [Source2ZE/CS2Fixes#239]
Starting up a new server and enabling over 100 maps in the maplist.cfg causes the server to go into limbo and crash. 

https://crash.limetech.org/qhusxkrthas7

![image](https://github.com/Source2ZE/CS2Fixes/assets/48465241/bbdef088-3d3a-4108-a71f-1461e31cf308)

**Comment by Vauff** [comment]
Link is bad?
![image](https://github.com/Source2ZE/CS2Fixes/assets/6075172/f1a011b7-690d-435e-bc02-3fcaf5541b3a)

**Comment by xLeviNx** [comment]
Is there a quick way to troubleshoot or figure out which ID? Currently they're all only S2ZE maps on the list

**Comment by xLeviNx** [comment]
https://crash.limetech.org/75vzplr6vza3

For some reason the crash dumps uploaded aren't fully uploaded with these crashes

**Comment by Vauff** [comment]
This was diagnosed on Discord, turns out there was indeed an invalid workshop ID in `maplist.cfg`.
