### ISSUE TITLE
After expire gag, mute, some players can't write/speak

### ISSUE THREAD

**Issue by mihaigsm2003** [Source2ZE/CS2Fixes#24]
After expire gag or mute some players can't speak or write in chat .If try ungag, say not gaged, also can't write in chat, only if player retry to server. If ungag first to expire infraction ungag work good to all players. Tested in 1-2 minutes

**Comment by xen-000** [comment]
It's hard to understand what you're saying, but this may be fixed. Do note that infractions are checked for expiry every 30 seconds to avoid having to write the infractions file too frequently.

**Comment by mihaigsm2003** [comment]
O see finally is solved, thanks!Pe 18 oct. 2023, la 00:32, xen ***@***.***> a scris:﻿
It's hard to understand what you're saying, but this may be fixed. Do note that infractions are checked for expiry every 30 seconds to avoid having to write the infractions file too frequently.
