### ISSUE TITLE
Finding offsets when new update or when missing

### ISSUE THREAD

**Issue by Gawnz1** [Source2ZE/CS2Fixes#240]
Hello,

How can we find offsets when new update is available and current offsets are not working? 
By offsets I mean for gamedata/cs2fixes.games.txt
I found https://github.com/a2x/cs2-dumper , but I am not fully sure is this the right method.

I am a new to srcds/cs2 and currently annoyed that after each kinda big update need to update the offsets, but it is what it is 😃
Can you guys share some methods if the above link is not right.

**Comment by Vauff** [comment]
Questions can go to our Discord in the future.

That cs2-dumper is for schema offsets, these are not really relevant, as we already have a schema implementation in code that finds these offsets at runtime (using reliable field names). Offsets in gamedata are rather usually (not always) VTable offsets, I'm not aware of any comprehensive guide for them, but did find https://wiki.alliedmods.net/User:Nosoop/Guide/Advanced#The_Hard_Way.
