### ISSUE TITLE
New CS2 update has broken the addon

### ISSUE THREAD

**Issue by DiDHack** [Source2ZE/CS2Fixes#250]
[CS2Fixes] Failed to find address for CBasePlayerController_SetPawn
[CS2Fixes] Failed to find address for ServerMovementUnlock
[CS2Fixes] Failed to find address for CheckJumpButtonWater
[CS2Fixes] Failed to find address for CategorizeUnderwater
[CS2Fixes] Failed to find address for WaterLevelGravity
[CS2Fixes] Failed to find address for CPhysBox_Use
[CS2Fixes] Failed to find address for BotNavIgnore
[CS2Fixes] Failed to find address for BotNavIgnore
[CS2Fixes] Failed to find address for BotNavIgnore
[CS2Fixes] Failed to find address for UTIL_SayTextFilter
[CS2Fixes] Failed to find address for UTIL_SayText2Filter
Failed to load plugin addons/cs2fixes/bin/linuxsteamrt64/cs2fixes (One or more address lookups, patches or detours failed, please refer to startup logs for more information).

**Comment by xLeviNx** [comment]
https://github.com/Source2ZE/CS2Fixes/actions/runs/9491150447

**Comment by DiDHack** [comment]
Super! Thanks!
