### ISSUE TITLE
!rtv leads to undefined map in the selection and further server crash

### ISSUE THREAD

**Issue by coolguy1337** [Source2ZE/CS2Fixes#253]
![изображение](https://github.com/Source2ZE/CS2Fixes/assets/172977114/cdfd9afb-aa8d-44ea-b75b-98b15b1e4ff3)
![изображение](https://github.com/Source2ZE/CS2Fixes/assets/172977114/525312ef-1af9-4fc6-b6b6-63e337510129)
![изображение](https://github.com/Source2ZE/CS2Fixes/assets/172977114/ce9d21a1-6cb1-4fc5-8f2d-8f9d2ef0e63a)

**Comment by Vauff** [comment]
Can you send your `maplist.cfg`? Also ensure you're running `host_workshop_collection` at server startup, sharing the collection too wouldn't hurt.

**Comment by Vauff** [comment]
Believe your issue is #268, will track it there.
