### ISSUE TITLE
CS2Fixes is not working on Windows Server anymore.

### ISSUE THREAD

**Issue by techtito** [Source2ZE/CS2Fixes#258]
Since last week update on CS2 the CS2Fixes stopped working in Windows Server based, even with an clean install, the server instant close after start.

**Comment by Vauff** [comment]
These issues weren't present at the time you reported this, but regardless, I just fixed and tested Windows is working in #274.

This specific issue wasn't actionable anyway, if you continue to have issues with the [dev build](https://github.com/Source2ZE/CS2Fixes/actions/runs/10336137678) or v1.8.9 (when it releases), please include crashdump information from Accelerator in your issue report.
