### ISSUE TITLE
CS2Fixes is not compatible with GOTV (crashes on startup)

### ISSUE THREAD

**Issue by Truyn** [Source2ZE/CS2Fixes#260]
In general, cs2fixes does not work, I tried to remove cssharp, as well as all other meta plugins, the server crashes after startup.
 I tried updating both cssharp and metamod, and redownloaded the cs2fixes mod itself.
and even if I leave it alone, the server still crashes after starting.
If you remove cs2fixes then everything works fine :(
What is written in the console below

 
 [Zombie:Reborn] The game is Humans vs. Zombies, the goal for zombies is to infect all humans by knifing them.
./game/cs2.sh: line 118:    45 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...

**Comment by axl303** [comment]
Try to get a dump or some more info.
You can use:
https://github.com/Source2ZE/AcceleratorCS2
https://github.com/komashchenko/AcceleratorLocal (Vauff gave me the link in one issue, if the 1st link is not working, try the second)
then share the crash stack trace.

**Comment by Truyn** [comment]
> Try to get a dump or some more info. You can use: https://github.com/Source2ZE/AcceleratorCS2 https://github.com/komashchenko/AcceleratorLocal (Vauff gave me the link in one issue, if the 1st link is not working, try the second) then share the crash stack trace.

Both of these plugins are not stable and can independently cause server crashes.

**Comment by axl303** [comment]
[02] Accelerator local (1.0.1) by Phoenix (˙·٠●Феникс●٠·˙), Asher Baker (asherkin)
  [03] AcceleratorCS2 (2.0.0) by Poggu, Phoenix (˙·٠●Феникс●٠·˙), asherkin

Both work fine for me, are you sure? You will use the plugin(s) to generate a dump only when the cs2fixes crash occurs?

**Comment by Poggicek** [comment]
> > Try to get a dump or some more info. You can use: https://github.com/Source2ZE/AcceleratorCS2 https://github.com/komashchenko/AcceleratorLocal (Vauff gave me the link in one issue, if the 1st link is not working, try the second) then share the crash stack trace.
> 
> Both of these plugins are not stable and can independently cause server crashes.

I am very much not aware of AcceleratorCS2 not being stable, it won't play nice with cs# (hence why I suggest against using both), but for debugging purposes they are perfectly fine to temporarily deploy. Only recorded problem between AcceleratorCS2 and cs# is creating crash dumps for handled exceptions by clr (e.g. throwing memory violations in c#), in 99% cases it's not an issue if you don't run plugins that ever throw such exceptions. Also there's exactly 0 reported cases of AcceleratorCS2 actually **crashing** a server.

**Comment by Vauff** [comment]
Diagnosed on Discord that they were running GOTV, which is known to break with CS2Fixes.

Poggu thinks it may be same issue as https://github.com/Source2ZE/GOTVCrashFix.

**Comment by Vauff** [comment]
Fixed in https://github.com/Source2ZE/CS2Fixes/commit/892bb8e6c01ee157d58dbe4460ab87971569ab62
