### ISSUE TITLE
Signature for X occurs multiple times

### ISSUE THREAD

**Issue by axl303** [Source2ZE/CS2Fixes#261]
[CS2Fixes] !!!!!!!!!! Signature for CBaseModelEntity_SetModel occurs multiple times! Using first match but this might end up crashing!
[CS2Fixes] !!!!!!!!!! Signature for BotNavIgnore occurs multiple times! Using first match but this might end up crashing!
[CS2Fixes] !!!!!!!!!! Signature for BotNavIgnore occurs multiple times! Using first match but this might end up crashing!

I have this notice for signatures when loading the plugin, using the latest release [v1.8.6](https://github.com/Source2ZE/CS2Fixes/releases/tag/v1.8.6)
The server runs okay tho.

**Comment by Poggicek** [comment]
Those are just warnings (We are aware of those and they're intentionally ignored), safe to ignore.

**Comment by xen-000** [comment]
For posterity, this means any similar warnings for _other_ signatures should not be ignored.
