### ISSUE TITLE
server crash when use c_beacon with rcon

### ISSUE THREAD

**Issue by sundog259** [Source2ZE/CS2Fixes#265]
> CSs_rcon c_beacon #65281
[Client] Asterismexecuted command c_beacon #65281.

> CSs_rcon c_beacon #65281
[Client] Asterism executed command c_beacon #65281.
[SteamNetSockets] [#* UDP steamid:8556*@123.* 'server'] 2 reply timeouts, last recv 6918.7ms ago.  Sending keepalive.
[SteamNetSockets] [#* UDP steamid:8556*@123.* 'server'] 2 reply timeouts, last recv 7119.5ms ago.  Sending keepalive.
[SteamNetSockets] [#* UDP steamid:8556*@123.* 'server'] 2 reply timeouts, last recv 7320.3ms ago.  Sending keepalive.
[SteamNetSockets] [#* UDP steamid:8556*@123.* 'server'] 3 reply timeouts, last recv 7521.2ms ago.  Sending keepalive.
[SteamNetSockets] [#* UDP steamid:8556*@123.* 'server'] 3 reply timeouts, last recv 7721.7ms ago.  Sending keepalive.
[SteamNetSockets] [#* UDP steamid:8556*@123.* 'server'] 4 reply timeouts, last recv 7923.0ms ago.  Sending keepalive.
[Client] CL:  WARNING:  Connection Problem, requesting uncompressed update

**Comment by Poggicek** [comment]
https://github.com/Source2ZE/CS2Fixes/blob/8af53eadf2f4ba5e9e8c0988f8e97c2b13eb87aa/src/leader.cpp#L827

`pPlayer->GetHandle()` isn't under a pPlayer null check

**Comment by Vauff** [comment]
Fixed in https://github.com/Source2ZE/CS2Fixes/commit/5fe7d5295cdb1248eb4cd859c57d3f0cb698c58e
