### ISSUE TITLE
Signatures help

### ISSUE THREAD

**Issue by Gawnz1** [Source2ZE/CS2Fixes#267]
Hello,

Is there any easy method to find signatures for functions.
For example, if I want to add some signature which is not available in gamedata, how do I find it?
I've red that some people are using Sigmaker and ida pro, but it seems much complicated to me.
Is there any simpler method that we can try and learn ourselves?

Cs2 updates are really annoying and especially when something signature which we might rely on as a function being broken.

Any help is highly appreciated!

**Comment by toorisrael** [comment]
You need ida pro x64 and leaked csgo source code for the start. Also, symbols build of dota2/csgo/cs2 could be useful.

**Comment by Vauff** [comment]
It's not really an easy process, though some signatures are "easier" due to having convenient string references directly in the functions. Issues aren't really the place for this though, if you're interested in learning you could ask in our Discord, or AlliedModders discord.
