### ISSUE TITLE
Error when entering

### ISSUE THREAD

**Issue by MasterWindowS** [Source2ZE/CS2Fixes#27]
I compiled the plugin, and when I try to login to the server it doesn't even start. It shows me all the messages that the plugin was successfully started but it won't let players in. Any solution?`[CS2Fixes] Found Source2GameEntities001 in server!

> [CS2Fixes] Found SchemaSystem_001 in schemasystem!
> [CS2Fixes] Removed hidden flags from 1357 convars
> [CS2Fixes] Removed hidden flags from 331 commands
> [CS2Fixes] Successfully patched ServerMovementUnlock at 00007FFB5D8022F4
> [CS2Fixes] Successfully patched VScriptEnable at 00007FFB8C65163A
> [CS2Fixes] Successfully initialized detour for Msg!
> [CS2Fixes] Successfully initialized detour for ConDMsg!
> [CS2Fixes] Successfully initialized detour for DevMsg!
> [CS2Fixes] Successfully initialized detour for Warning!
> [CS2Fixes] Successfully initialized detour for DevWarning!
> [CS2Fixes] Successfully initialized detour for LoggingSystem_Log!
> [CS2Fixes] Successfully initialized detour for LoggingSystem_LogDirect!
> [CS2Fixes] Successfully initialized detour for LoggingSystem_LogAssert!
> [CS2Fixes] Successfully initialized detour for UTIL_SayTextFilter!
> [CS2Fixes] Successfully initialized detour for UTIL_SayText2Filter!
> [CS2Fixes] Successfully initialized detour for Host_Say!
> [CS2Fixes] Successfully initialized detour for IsHearingClient!
> [CS2Fixes] Successfully initialized detour for CSoundEmitterSystem_EmitSound!
> [CS2Fixes] Successfully initialized detour for CCSWeaponBase_Spawn!
> [CS2Fixes] Successfully initialized detour for TriggerPush_Touch!
> Loaded admin MasterWindowS
>  - Steam ID 500725694
>  - Flags     z
> Failed to load addons/cs2fixes/data/infractions.txt
> [CS2Fixes] g_gameEventManager - 00007FFB5E40D4E0
> ResetBreakpadAppId: Universe is 0 (k_EUniverseInvalid)
> ResetBreakpadAppId: Setting dedicated server app id: 2347773
>  
> InitSteamLogin_Internal: Initializing breakpad.
> Steam Universe is invalid, possibly asking before Steam was successfully initialized.
> ResetBreakpadAppId: Universe is 0 (k_EUniverseInvalid)
> ResetBreakpadAppId: Setting dedicated server app id: 2347773
> Visibility enabled.
> USRLOCAL path not found!
> Trying to set dxlevel (111) which is higher than the card can support (110)!
> ---------------
> Path ID:             File Path:
> ADDONS               "game\csgo_addons\"
> CONTENT              "content\csgo\addons\metamod\"
> CONTENT              "content\csgo\"
> CONTENT              "content\csgo_imported\"
> CONTENT              "content\csgo_core\"
> CONTENT              "content\core\"
> CONTENTADDONS        "content\csgo_addons\"
> CONTENTROOT          "content\"
> DEFAULT_WRITE_PATH   "game\csgo\addons\metamod\"
> EXECUTABLE_PATH      "game\bin\win64\"
> EXECUTABLE_PATH      "game\bin\"
> GAME                 "game\csgo\pak01.vpk" (vpk) game\csgo\pak01.vpk
> GAME                 "game\csgo_imported\pak01.vpk" (vpk) game\csgo_imported\pak01.vpk
> GAME                 "game\csgo_core\pak01.vpk" (vpk) game\csgo_core\pak01.vpk
> GAME                 "game\core\pak01.vpk" (vpk) game\core\pak01.vpk
> GAME                 "game\csgo\shaders_pc.vpk" (vpk) game\csgo\shaders_pc.vpk
> GAME                 "game\csgo_core\shaders_pc.vpk" (vpk) game\csgo_core\shaders_pc.vpk
> GAME                 "game\core\shaders_pc.vpk" (vpk) game\core\shaders_pc.vpk
> GAME                 "game\csgo\addons\metamod\"
> GAME                 "game\csgo\"
> GAME                 "game\csgo_imported\"
> GAME                 "game\csgo_core\"
> GAME                 "game\core\"
> GAMEBIN              "game\csgo\addons\metamod\bin\win64\"
> GAMEBIN              "game\csgo\addons\metamod\bin\"
> GAMEBIN              "game\csgo\bin\win64\"
> GAMEBIN              "game\csgo\bin\"
> GAMEBIN              "game\csgo_imported\bin\win64\"
> GAMEBIN              "game\csgo_imported\bin\"
> GAMEBIN              "game\csgo_core\bin\win64\"
> GAMEBIN              "game\csgo_core\bin\"
> GAMEBIN              "game\core\bin\win64\"
> GAMEBIN              "game\core\bin\"
> GAMEROOT             "game\"
> MOD                  "game\csgo\pak01.vpk" (vpk) game\csgo\pak01.vpk
> MOD                  "game\csgo_imported\pak01.vpk" (vpk) game\csgo_imported\pak01.vpk
> MOD                  "game\csgo_core\pak01.vpk" (vpk) game\csgo_core\pak01.vpk
> MOD                  "game\csgo\"
> MOD                  "game\csgo_imported\"
> MOD                  "game\csgo_core\"
> PLATFORM             "game\core\pak01.vpk" (vpk) game\core\pak01.vpk
> PLATFORM             "game\core\"
> SHADER_SOURCE        "src\shaders\csgo\addons\metamod\"
> SHADER_SOURCE        "src\shaders\csgo\"
> SHADER_SOURCE        "src\shaders\csgo_imported\"
> SHADER_SOURCE        "src\shaders\csgo_core\"
> SHADER_SOURCE        "src\shaders\core\"
> SHADER_SOURCE_MOD    "src\shaders\csgo\addons\metamod\"
> SHADER_SOURCE_ROOT   "src\shaders\"`

**Comment by Poggicek** [comment]
We only process issues with the actual cs2fixes code, not user errors. This issue is not even informative enough to provide any help even if we wanted to.
