### ISSUE TITLE
CS2Fixes 1.8.8 windows server version, crash server

### ISSUE THREAD

**Issue by sunrisecz** [Source2ZE/CS2Fixes#273]
[c31313b1-73e6-4137-a2f5-00a93177a73e.dmp.txt](https://github.com/user-attachments/files/16568309/c31313b1-73e6-4137-a2f5-00a93177a73e.dmp.txt)

**Comment by sunrisecz** [comment]
[2546df49-44a1-4b99-abfb-99228e95b454.dmp.txt](https://github.com/user-attachments/files/16568484/2546df49-44a1-4b99-abfb-99228e95b454.dmp.txt)

**Comment by sunrisecz** [comment]
works fine!

**Comment by Vauff** [comment]
Glad to hear you got it working earlier, but I just identified and fixed several more Windows issues in #274. Feel free to try out the [dev build](https://github.com/Source2ZE/CS2Fixes/actions/runs/10336137678).
