### ISSUE TITLE
Crash game with custom skin

### ISSUE THREAD

**Issue by Runo231** [Source2ZE/CS2Fixes#276]
Every time I change the skin with some plugin that allows changing player skins, it makes the game crash, I have tried several plugins and with all of them the game crashes.

It can be replicated by having a player or a bot shoot you while you have a skin on and change teams, I can indicate a video if it is better.

Please I need to fix this.
Thanks.

**Comment by xen-000** [comment]
How is this related to CS2Fixes? Also we don't support any skin changers here.
