### ISSUE TITLE
8/20/2024 CS2 update  windows version,  crash server 

### ISSUE THREAD

**Issue by sunrisecz** [Source2ZE/CS2Fixes#280]
[3ab9209a-e4dc-4e79-ad7d-158c98b6aa1f.dmp.txt](https://github.com/user-attachments/files/16684899/3ab9209a-e4dc-4e79-ad7d-158c98b6aa1f.dmp.txt)

**Comment by vstrg** [comment]
there is ip and server token in the file, I think you should edit the file and upload it.

**Comment by Vauff** [comment]
Can you try this [dev build](https://github.com/Source2ZE/CS2Fixes/actions/runs/10482969699)? The update should've just errored instead of crashing, but without testing more, not sure what else would have broken on Windows only.

**Comment by vstrg** [comment]
tried with dev build it seems to work for me.

**Comment by sunrisecz** [comment]
The test works fine. thanks!
