### ISSUE TITLE
Particles problems

### ISSUE THREAD

**Issue by byerbasan** [Source2ZE/CS2Fixes#282]
Hello,

I cant use beacon, defend commands, commands run but nothing happens. My client console outputs these errors:

[Particles] WARNING: Particle system 'particles/cs2fixes/player_beacon.vpcf' was not precached correctly. Performing blocking load....

[Particles] WARNING: Particle system 'particles/cs2fixes/leader_defend_mark.vpcf' was not precached correctly. Performing blocking load....

Using latest CS2Fixes

**Comment by Vauff** [comment]
You need to use [MultiAddonManager](https://github.com/Source2ZE/MultiAddonManager) to make custom assets available to clients. You can either use [our addon](https://steamcommunity.com/sharedfiles/filedetails/?id=3157463861), or create your own addon using the compiled assets in the release.

**Comment by byerbasan** [comment]
> You need to use [MultiAddonManager](https://github.com/Source2ZE/MultiAddonManager) to make custom assets available to clients. You can either use [our addon](https://steamcommunity.com/sharedfiles/filedetails/?id=3157463861), or create your own addon using the compiled assets in the release.

already using

// Extra addon settings, this is only executed once on plugin load
mm_extra_addons 				"3157463861"		// The workshop IDs of extra addons, separated by commas (e.g. "3090239773,3070231528")
mm_extra_addons_timeout			10		// How long until clients are timed out in between connects for extra addons, requires mm_extra_addons to be used
mm_addon_mount_download			0		// Whether to download an addon upon mounting even if it's installed

**Comment by Vauff** [comment]
Seems like it's outdated, I've asked and it should be updated soon with latest CS2Fixes assets.

**Comment by byerbasan** [comment]
> Seems like it's outdated, I've asked and it should be updated soon with latest CS2Fixes assets.

Thanks, assets updated on server too but still not working same issue and it spams my client console, i also removed my CS2 and reinstalled again.

[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_defend_mark.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load....
[Particles] WARNING: Particle system 'particles/cs2fixes/leader_tracer.vpcf' was not precached correctly. Performing blocking load...
