### ISSUE TITLE
[Question] Teamscore reset question

### ISSUE THREAD

**Issue by axl303** [Source2ZE/CS2Fixes#290]
Hello, 

This might be not fully for here, but I am bugging my head couple of days trying to figure out how I can really make the team scores to not reset like described as in that issue: https://github.com/Source2ZE/CS2Fixes/issues/213

I tried contacting in discord, but no one told something as an idea..

Also, https://github.com/Source2ZE/CS2Fixes/issues/213#issuecomment-2081382018, how can this even be done without the addon? Is it some cvar or?

I will be very happy if someone can help to keep the game team scores. I've blocked `Game commencing/GameStart`, but it is too late and reset is still triggered..

Can someone point me where or for what should I look, is it Win conditions check or something else.. I am out of ideas.. :(

**Comment by Poggicek** [comment]
Github Issues are meant for reporting **issues** related to **CS2Fixes**. The response Vauff sent to your previous issue was saying that the score resetting on join is CS2 behavior and not related to CS2Fixes (As making an issue here suggests that it is). I am closing this issue for the same reason the previous one was closed.

**Comment by Vauff** [comment]
You could save & restore the value of [this schema field](https://github.com/Source2ZE/CS2Fixes/blob/4563f04efec68980240b86d3b9faad61295f1a7f/src/cs2_sdk/entity/cteam.h#L34) yourself. There's some example CS2Fixes usage in `zombiereborn.cpp`.
