### ISSUE TITLE
Update from 2 October broke the plugins

### ISSUE THREAD

**Issue by DiDHack** [Source2ZE/CS2Fixes#300]
The error:
`/cs2fixes.so: undefined symbol: AssertValidStringPtr`
when you try to load plugin.

**Comment by xen-000** [comment]
Yes, we know. It needs a rebuild after hl2sdk gets updated, then we need to fix all the broken signatures and offsets.

**Comment by DiDHack** [comment]
https://github.com/alliedmodders/metamod-source/issues/193 workaround

**Comment by xen-000** [comment]
Feel free to use the workaround yourself to compile plugins. We won't release without an actual update to the sdk and even then there's a lot of broken signatures.

**Comment by DiDHack** [comment]
No problem ✌️

**Comment by DiDHack** [comment]
SDK is updated.

**Comment by Vauff** [comment]
> SDK is updated.

`IGameSystem` is still broken in SDK which we rely on.

**Comment by raszyniaczek** [comment]
Official is now works. Metamod build 1314 now we need to wait for CounterStrikeSharp update :)

**Comment by Vauff** [comment]
There's a dev build now available in https://github.com/Source2ZE/CS2Fixes/pull/302, still expect some issues.

**Comment by DiDHack** [comment]
Thanks! Compiled! Works at first view!

**Comment by Vauff** [comment]
Fixed in [v1.9](https://github.com/Source2ZE/CS2Fixes/releases/tag/v1.9).
