### ISSUE TITLE
Team colors for servers with more than 10 slots

### ISSUE THREAD

**Issue by crashzk** [Source2ZE/CS2Fixes#314]
CS2 servers with more than 10 slots the colors of the players on the team do not work, CT is blue and TR is orange, this applies to everyone. 10 slots player colors work normally.

Would it be possible to fix something to trick the `-maxplayers` command, even though there are more than 10 slots, it still shows the colors of the players on the teams?

In a survey, questions were returned with this information: https://github.com/a2x/cs2-dumper/blob/main/output/server_dll.cs#L10097
```
check this https://github.com/a2x/cs2-dumper/blob/main/output/server_dll.cs#L10097

idk if it's related to the actual color and if it can assign more than the 10 colors that are used for mm 
```

**Comment by Vauff** [comment]
I don't think we would be interested in pursuing this.

**Comment by crashzk** [comment]
I see, I thought it would be interesting to have a cvar to disable and enable if we want to use this function.

Anyway, maybe a separate plugin later, in any case thanks.
