### ISSUE TITLE
Crash on startup since 2024-10-28 Update

### ISSUE THREAD

**Issue by KewaiiGamer** [Source2ZE/CS2Fixes#319]
I attached my config for reference.

Server crashes on every startup.

[cs2fixes.txt](https://github.com/user-attachments/files/17553928/cs2fixes.txt)

**Comment by Vauff** [comment]
Fixed inhttps://github.com/Source2ZE/CS2Fixes/commit/f99a586a7a593362ed914ee98939450ab0f033b2 and v1.9.3.
