### ISSUE TITLE
[BUG?] Server crashed when starting

### ISSUE THREAD

**Issue by DearCrazyLeaf** [Source2ZE/CS2Fixes#320]
![1b2fe4c5664fb19bc330a0de3fdc0741](https://github.com/user-attachments/assets/68f3706d-92c2-4e44-abfa-a826c0e9ac73)

**Comment by xyzelt** [comment]
Failed to find address for CheckJumpButtonWater ?
Signature won't fit

**Comment by DearCrazyLeaf** [comment]
@Vauff

**Comment by Vauff** [comment]
Fixed in https://github.com/Source2ZE/CS2Fixes/commit/f99a586a7a593362ed914ee98939450ab0f033b2 and v1.9.3.
