### ISSUE TITLE
[BUG] Crashed On Loading After Latest Update

### ISSUE THREAD

**Issue by DearCrazyLeaf** [Source2ZE/CS2Fixes#329]
Unloading CS2Fixes and server runs well.

**Comment by xen-000** [comment]
Yes, we're aware of this. We'll release a new version after the sdk is fixed.

**Comment by Vauff** [comment]
A proper SDK fix is estimated to be days out, so we are going to work on a stopgap release with some features disabled.

**Comment by Vauff** [comment]
https://github.com/Source2ZE/CS2Fixes/releases/tag/v1.10.1
