### ISSUE TITLE
Not compiled for windows

### ISSUE THREAD

**Issue by Levchik97** [Source2ZE/CS2Fixes#4]
Not compiled for windows:

�ਬ�砭��: ����祭�� 䠩��:  C:\Code_Compile\hl2sdk-cs2\public\tier0/memdbgon.h
C:\Code_Compile\CS2Fixes\commands.cpp(248): error C2059: ᨭ⠪��᪠� �訡��: delete
C:\Code_Compile\CS2Fixes\commands.cpp(249): error C2059: ᨭ⠪��᪠� �訡��: }
C:\Code_Compile\CS2Fixes\commands.cpp(249): error C2143: ᨭ⠪��᪠� �訡��: ������⢨� ";" ��। "}"
C:\Code_Compile\CS2Fixes\commands.cpp(255): error C2143: ᨭ⠪��᪠� �訡��: ������⢨� ";" ��। "{"
C:\Code_Compile\CS2Fixes\commands.cpp(255): error C2447: {: ��������� ��������� �㭪樨 (��������, �ᯮ������ �ଠ��� ᯨ᮪ ��ண� ⨯�)

cl: ��������� ��ப� warning D9025: ��८�।������ "/Zi" �� "/Z7"
Build failed: cs2fixes\windows-x86_64\commands.obj

**Comment by Vauff** [comment]
Hi, please use our [Discord](https://discord.gg/QsSGf9ZEVs) for realtime support instead, assuming you have [read the disclaimer and have a contribution to the project](https://github.com/Source2ZE/CS2Fixes#disclaimer-this-plugin-is-not-meant-to-be-used-on-a-server-yet-it-is-very-much-a-work-in-progress-and-thus-we-are-not-responsible-for-any-issues-or-breakages-caused-by-the-plugin-in-addition-we-will-not-provide-support-for-building-or-usage-unless-you-plan-on-contributing-to-the-project-yourself).
