### ISSUE TITLE
Kick issue

### ISSUE THREAD

**Issue by asdfxD** [Source2ZE/CS2Fixes#56]
did not happen to me, but happens to some of my admins. he tries to kick an afk player and two times the wrong players have been kicked.

L 10/19/2023 - 21:42:28: "ADMIN<1><[U:1:XXX]><TERRORIST>" say "!kick ♥Panda☯Baby ♥"
L 10/19/2023 - 21:42:28: "󠁳⁧⁧ WRONGPLAYER<2><[U:1:XXX]><CT>" disconnected (reason "NETWORK_DISCONNECT_KICKED")

L 10/19/2023 - 21:43:00: "ADMIN<1><[U:1:XXX]><TERRORIST>" say "!kick ♥Panda☯Baby ♥"
L 10/19/2023 - 21:43:00: "WRONGPLAYER2<5><[U:1XXX]><CT>" disconnected (reason "NETWORK_DISCONNECT_KICKED")

**Comment by Vauff** [comment]
Very likely due to handling of special unicode characters, userid targeting should still work fine. This would cause issues on SourceMod too.
