### ISSUE TITLE
load problem

### ISSUE THREAD

**Issue by exababy** [Source2ZE/CS2Fixes#58]
meta load /game/csgo/addons/cs2fixes/bin/linuxsteamrt64/cs2fixes.so

metamod version : 1247

[CS2Fixes] Starting plugin.
All hooks started!
[CS2Fixes] Loading addons/cs2fixes/gamedata/cs2fixes.games.txt for game: csgo
[CS2Fixes] Initialized module engine2 base: 0x7fdd88bf2000 | size: 4534272
[CS2Fixes] Initialized module tier0 base: 0x7fdd8a4f6000 | size: 3084288
[CS2Fixes] Initialized module server base: 0x7fdd5e67e000 | size: 14286848
[CS2Fixes] Initialized module schemasystem base: 0x7fdd7699b000 | size: 303104
[CS2Fixes] Initialized module vscript base: 0x7fdd66be1000 | size: 741376
[CS2Fixes] Failed to find address for UTIL_Remove
[CS2Fixes] Found GameResourceServiceServerV001 in engine2!
[CS2Fixes] Found VEngineCvar007 in tier0!
[CS2Fixes] Found Source2GameEntities001 in server!
[CS2Fixes] Found SchemaSystem_001 in schemasystem!
[CS2Fixes] All hooks started!
[CS2Fixes] Removed hidden flags from 0 convars
[CS2Fixes] Removed hidden flags from 8 commands
[CS2Fixes] Failed to find address for ServerMovementUnlock
[CS2Fixes] Failed to find address for VScriptEnable
[CS2Fixes] Failed to find address for CategorizeUnderwater
[CS2Fixes] Failed to find address for WaterLevelGravity
[CS2Fixes] Successfully initialized detour for Msg!
[CS2Fixes] Successfully initialized detour for ConDMsg!
[CS2Fixes] Successfully initialized detour for DevMsg!
[CS2Fixes] Successfully initialized detour for Warning!
[CS2Fixes] Successfully initialized detour for DevWarning!
[CS2Fixes] Successfully initialized detour for LoggingSystem_Log!
[CS2Fixes] Successfully initialized detour for LoggingSystem_LogDirect!
[CS2Fixes] Successfully initialized detour for LoggingSystem_LogAssert!
[CS2Fixes] Failed to find address for UTIL_SayTextFilter
funchook_install error for UTIL_SayTextFilter: 2 
[CS2Fixes] Failed to find address for UTIL_SayText2Filter
funchook_install error for UTIL_SayText2Filter: 2 
[CS2Fixes] Failed to find address for Host_Say
funchook_install error for Host_Say: 2 
[CS2Fixes] Failed to find address for IsHearingClient
funchook_install error for IsHearingClient: 2 
[CS2Fixes] Failed to find address for CSoundEmitterSystem_EmitSound
funchook_install error for CSoundEmitterSystem_EmitSound: 2 
[CS2Fixes] Failed to find address for CCSWeaponBase_Spawn
funchook_install error for CCSWeaponBase_Spawn: 2 
[CS2Fixes] Failed to find address for TriggerPush_Touch
funchook_install error for TriggerPush_Touch: 2

**Comment by xen-000** [comment]
Why are you loading it from the console, it should be already loaded if everything was setup properly. It looks like the plugin was loaded twice here.

**Comment by exababy** [comment]
yes i fixed now right team select menu crashing game
