### ISSUE TITLE
Sigscanning breaks on string containing null bytes

### ISSUE THREAD

**Issue by zer0k-z** [Source2ZE/CS2Fixes#6]
The commonly used makesig script in IDA can create strings with null bytes inside of it. This is a problem because `V_strlen` will stop at the first null byte it sees, therefore cutting the real signature short.
[My solution](https://github.com/zer0k-z/cs2kz_metamod/commit/65ed9703469f3ac9a98240919068ee15a7494e0d) to this problem involves using this struct to generates the length, but I figure there might be smarter way for this as well:
```c++
// Actual credit to Szwagi
struct Signature {
	const char *data = nullptr;
	size_t length = 0;

	template<size_t N>
	Signature(const char(&str)[N]) {
		data = str;
		length = N - 1;
	}
};
```

**Comment by Poggicek** [comment]
I believe gamedata pr should have this sorted out
