### ISSUE TITLE
Does not recognise special characters

### ISSUE THREAD

**Issue by exababy** [Source2ZE/CS2Fixes#66]
If there is a person using special characters, it gives an invalid duration error.

!ban Таль толстая шлюх 1

invalid duration.

**Comment by exababy** [comment]
and userid does not work, userids must work to solve the problem.

**Comment by Poggicek** [comment]
> If there is a person using special characters, it gives an invalid duration error.
> 
> !ban Таль толстая шлюх 1
> 
> invalid duration.

There literally is a space in the name.

**Comment by exababy** [comment]
!ban slotid 1 

invalid name

!ban Таль  1 

same

**Comment by Poggicek** [comment]
that's not how you targer userid

**Comment by exababy** [comment]
how can I do it?

**Comment by xen-000** [comment]
You prepend the userid with #, just like in sourcemod. So `!ban #1`

**Comment by exababy** [comment]
thanks
