### ISSUE TITLE
cant hear weapons correctly

### ISSUE THREAD

**Issue by ghostt187** [Source2ZE/CS2Fixes#67]
all weapons from the enemies pov sound like usp... for example enemy is shooting with an m4 and i hear it as if it is a usp

**Comment by xen-000** [comment]
Yes, this is intended as it's targeted towards ZE. Players can toggle with `!stopsound`, or if you don't want it at all you can remove the command and change this to 0 in your build. https://github.com/Source2ZE/CS2Fixes/blob/d0e91e22d4c52ec32266791cf2a5d12a919d20f5/src/playermanager.h#L105
