### ISSUE TITLE
Players Stay like ghost players even when they leave

### ISSUE THREAD

**Issue by ghostt187** [Source2ZE/CS2Fixes#76]
When players joins and if he leave player number doesnt go down and in servers console says Nickname STEAM:ID:PENDING 
[https://imgur.com/a/TsTioDl](url)
here u can see players online are 5vs4 but scoreboard number says there are 6 vs 5 this happens and if there are 10vs10 if other players have joined before and left it would be like 15vs16 on the scoreboard... i hope u understand what im saying

**Comment by Poggicek** [comment]
I believe this is a behaviour caused by cs2, completely unrelated to cs2fixes

**Comment by ghostt187** [comment]
it started right after adding cs2fixes so thats why i thought maybe its cs2fixes problem
