### ISSUE TITLE
Database support for infractions and admins

### ISSUE THREAD

**Issue by zonical** [Source2ZE/CS2Fixes#8]
Kia ora, I thought I would post this hear instead of pinging the main contributors on Discord so we have a centralized discussion point.

In line with previous SourceMod admin systems, I think it would be a good idea to integrate saving infractions and admin privileges to a database. An obvious pro would be that infraction and admin data would be shared across servers. I've been doing some experimentation with integrating the MySQL 5.7 C API into a MM plugin with some successful results.

I'd love to hear other peoples opinions. I know the project is still heavily WIP and completely subject to change so perhaps adding a system like this may not be the best choice right now.

**Comment by xen-000** [comment]
This would be a nice feature, but it's very much out of scope for this plugin. Something like this should be in a dedicated plugin for admin features (or better yet, a plugin just for DB interaction), and right now I'm not planning on separating those admin features out.
