### ISSUE TITLE
mp_solid_teammates not work with cs2fixes

### ISSUE THREAD

**Issue by ghostt187** [Source2ZE/CS2Fixes#81]
0-1-2 are doing all the same thing if i run to knife a enemy im able to go thru him

**Comment by Poggicek** [comment]
Yes, that's a feature of cs2fixes.

**Comment by ghostt187** [comment]
how do disable it?

> Yes, that's a feature of cs2fixes.

**Comment by asdfxD** [comment]
Why not remove this from cs2fixes? There is a server cvar for server owners

**Comment by Hichatu** [comment]
mp_solid_teammates 0 is not sufficient enough for fixing elevators and moving platforms on ZE. As such the plugin changes the collision type of players to debris.

**Comment by ghostt187** [comment]
anyone has any clue how do i disable this feature from cs2fixes so i can work with that command?

**Comment by xLeviNx** [comment]
Please understand this is tailored to Zombie Escape. If you have a certain need, search in the code (Xen and Poggu did a phenomenal job commenting sections in the code and you can manually disable it yourself).
