### ISSUE TITLE
Is this a crash waiting to happen?

### ISSUE THREAD

**Issue by roge** [Source2ZE/CS2Fixes#82]
What if `rand() % spawns.Count() + 1` = `spawns.Count()`?

https://github.com/Source2ZE/CS2Fixes/blob/bc2701fb88b124de49a6e6dbc55bba7ab6571f56/src/commands.cpp#L278-L280

Shouldn't it just be `rand() % spawns.Count()`?

**Comment by Poggicek** [comment]
Yes that will indeed crash, will fix asap
