### ISSUE TITLE
plugin not loading after newest update

### ISSUE THREAD

**Issue by gardc** [Source2ZE/CS2Fixes#84]
Updated to latest version of the game server, clean install. Installed latest metamod, which loads just fine. But cs2fixes does not load, instead here is what's listed when I run `meta list`:
```
meta list
Listing 1 plugin:
  [01] <FAILED>
```
![Screenshot 2023-11-03 035800](https://github.com/Source2ZE/CS2Fixes/assets/41453409/dbcdaa33-e615-44da-a82c-8cca200be40c)

Compiled on Windows, metamod-source and hl2sdk (cs2 branch) on latest versions as of 11/3/23 03:00GMT.

**Comment by xLeviNx** [comment]
Aware~

**Comment by asdfxD** [comment]
metamod does not load, so cs2fixes wont load.

**Comment by Yarukon** [comment]
gamedata needs to update

**Comment by gardc** [comment]
working after latest commit
