### ISSUE TITLE
Question: Map specific configs

### ISSUE THREAD

**Issue by Veeksi** [Source2ZE/CS2Fixes#89]
Hey, great work in a such a stort time! (e.g. rcon support is amazing)

Just a small question: 
- is it currently possible to execute / override map specific configs?

Here is a short snippet that shows what is executed in an order when map is started:
```
[CS2Fixes] Hook_StartupServer: Running map config for aim_redline_cs2
[CS2Fixes] OnLevelInit(aim_redline_cs2)
exec: couldn't exec '{*}cfg/skill1.cfg', unable to read file
execing server_default.cfg
execing server.cfg
execing gamemode_custom.cfg
exec: couldn't exec '{*}cfg/gamemode_custom_server.cfg', unable to read file
execing maps/aim_redline_cs2.cfg
execing maps/aim_redline_cs2
```

So basically if the aim_redline_cs2 map has configured `bot_quota 5`, I would love to be able to override that and execute map specific config that contains `bot_quota 10`.

**Comment by Vauff** [comment]
https://github.com/Source2ZE/CS2Fixes/commit/ba44477e134b27e9c25ceb2447fe1f29ee37194a will land in main branch when ZR is finished.
